# Generated by Django 4.2.5 on 2023-09-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sem Tag', max_length=50)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
