# Generated by Django 4.2.5 on 2023-09-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
